-- Driver profile: personal, address, license, and emergency contact fields

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS last_name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS phone_type text,
  ADD COLUMN IF NOT EXISTS physical_address_line1 text,
  ADD COLUMN IF NOT EXISTS physical_address_line2 text,
  ADD COLUMN IF NOT EXISTS physical_city text,
  ADD COLUMN IF NOT EXISTS physical_state text,
  ADD COLUMN IF NOT EXISTS physical_postal_code text,
  ADD COLUMN IF NOT EXISTS mailing_same_as_physical boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS mailing_address_line1 text,
  ADD COLUMN IF NOT EXISTS mailing_address_line2 text,
  ADD COLUMN IF NOT EXISTS mailing_city text,
  ADD COLUMN IF NOT EXISTS mailing_state text,
  ADD COLUMN IF NOT EXISTS mailing_postal_code text,
  ADD COLUMN IF NOT EXISTS drivers_license_number text,
  ADD COLUMN IF NOT EXISTS drivers_license_state text,
  ADD COLUMN IF NOT EXISTS drivers_license_exp_month integer,
  ADD COLUMN IF NOT EXISTS drivers_license_exp_day integer,
  ADD COLUMN IF NOT EXISTS drivers_license_exp_year integer,
  ADD COLUMN IF NOT EXISTS dob_month integer,
  ADD COLUMN IF NOT EXISTS dob_day integer,
  ADD COLUMN IF NOT EXISTS dob_year integer,
  ADD COLUMN IF NOT EXISTS ssn text,
  ADD COLUMN IF NOT EXISTS hair_color text,
  ADD COLUMN IF NOT EXISTS eye_color text,
  ADD COLUMN IF NOT EXISTS height_feet integer,
  ADD COLUMN IF NOT EXISTS height_inches integer,
  ADD COLUMN IF NOT EXISTS weight_lbs integer,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS emergency_contact_first_name text,
  ADD COLUMN IF NOT EXISTS emergency_contact_last_name text,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone text,
  ADD COLUMN IF NOT EXISTS emergency_contact_phone_type text,
  ADD COLUMN IF NOT EXISTS emergency_contact_relation text;

COMMENT ON COLUMN public.profiles.ssn IS 'Sensitive PII — restrict admin access in application layer';